### ISSUE TITLE
issues001

### ISSUE THREAD

**Issue by Aliffter** [LGCooci/LGiOSQuestions#3]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/66396195/114967805-b3e83a00-9ea7-11eb-8838-7e240fce64c3.png">

老师您好，这里应该是不是有点小问题，
如果是isTaggedPointer，就直接返回了
如果是nonpointer。 并且有下面四种任意一种，会调用object_dispose
如果只是nonpointer。下面四种情况都没有，并不会调用object_dispose，而是直接free

**Comment by LGCooci** [comment]
是的额
